# Generated by Django 5.2.8 on 2025-11-22 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_comment_image_comment_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Direct Message', 'verbose_name_plural': 'Direct Messages'},
        ),
        migrations.AddField(
            model_name='directmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dm_images/'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('VOICE', 'Voice Note'), ('POST', 'Shared Post')], default='TEXT', max_length=10),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='dm_videos/'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='voice_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='dm_voice/'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='directmessage',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='feed.conversation'),
        ),
    ]
